### ISSUE TITLE
Not working with Safari and El Capitan

### ISSUE THREAD

**Issue by jllodra** [kopurando/virga.app-youtube-dl-GUI-for-OS-X#3] opened 2016-04-24 14:00 UTC
Hi again,

sorry to report a new bug, but it seems it is not working with Safari.
When I open virga.app my Google Chrome opens (with a blank url) and the download fails.

Thanks in advance.

**Comment by kopurando** [comment] 2016-04-24 14:01
what version of Safari do you use?

**Comment by jllodra** [comment] 2016-04-24 14:03
<img width="277" alt="screen shot 2016-04-24 at 16 03 06" src="https://cloud.githubusercontent.com/assets/273590/14768030/14d143ae-0a36-11e6-92c2-0afa6642af7a.png">

**Comment by kopurando** [comment] 2016-04-24 14:05
i use 9.1 and it works, will check with Chrome closed later... too many tabs open atm :)

**Comment by jllodra** [comment] 2016-04-24 14:09
Ok, thanks. Tested also on another machine with Safari 9.1 and not working either.

**Comment by TaciteOFF** [comment] 2016-05-08 17:06
Doesn't work with Safari Technology Preview either
Version 9.1.1 (11601.6.17, 11602.1.29)

**Comment by kopurando** [comment] 2016-05-09 12:38
thanks for reporting, I found what the issue is (seems like AppleScript's handling of frontmost windows changed in recent builds of El Capitan), will roll out a fix tonight.

**Comment by kopurando** [comment] 2016-05-09 14:26
Fixed in 1.0.5, please test
https://github.com/kopurando/virga.app-youtube-dl-GUI-for-OS-X/releases/tag/1.0.5

**Closed as completed by kopurando** 2016-05-09 14:26 UTC
